-- AlterTable
ALTER TABLE "Borrowing" ADD COLUMN     "timeStamps" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Customer" ADD COLUMN     "timeStamps" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Equiment" ADD COLUMN     "timeStamps" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Manager" ADD COLUMN     "timeStamps" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Reservation" ADD COLUMN     "timeStamps" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
